<?php

use App\Career;
use Illuminate\Database\Seeder;

class CareerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $careers = array(
            array(
                "id" => 1,
                "title" => "Account Manager",
                "slug" => "account-manager",
                "department" => "Sales",
                "experience" => "1",
                "banner" => "account-manager-60d441841950e.png",
                "overview" => "<ul>\n<li>Manage and develop a portfolio of accounts</li>\n<li>Lead generation and account development</li>\n<li>Manage customers &amp; client relationships, promptly respond to queries, ensure promises are kept and manage expectations.</li>\n<li>Achieve sales targets and objectives</li>\n<li>Attend client meetings and do regular customer visits</li>\n<li>Maintain and build relationships with existing clients</li>\n<li>Accomplish administrative work and reports.</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree, any field.</li>\n<li>With excellent communication skills.</li>\n<li>At least 1 year(s) of working experience in the corporate sales is required for this position.</li>\n<li>Amenable to work in Ayala, Makati</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"Account Manager\",\"meta_description\":\"Account Manager\",\"meta_keywords\":\"Account Manager\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 2,
                "title" => "Digital Marketing Associate",
                "slug" => "digital-marketing-associate",
                "department" => "Marketing",
                "experience" => "1",
                "banner" => "digital-marketing-associate-60d441b70f17f.png",
                "overview" => "<ul>\n<li>Social media management of clients&rsquo; accounts.</li>\n<li>Responsible for the development of customers' digital marketing pitch and plans</li>\n<li>Coordinates and negotiates with partners and suppliers</li>\n<li>Coordinates with sales, creatives and development teams regarding customer's project updates and customer's digital presence analytics.</li>\n<li>Monitors customers ad placement</li>\n<li>Monitors clients&rsquo; digital presence and online reputation</li>\n<li>Monitors competitors&rsquo; activity</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree, Advertising/Media, Journalism, Business Studies/Administration/Management, Mass Communications, Marketing or equivalent.</li>\n<li>Must have an excellent conceptualization and analytical skills</li>\n<li>Excellent written and oral communication skill.</li>\n<li>Must be proficient in Adobe Photoshop</li>\n<li>Preferably with at least 6 months to 1 year digital marketing work-related experience.</li>\n<li>Open to Fresh Graduates with exceptional scholastic record or with digital marketing related internship.</li>\n<li>Applicants must be willing to work in Makati City.</li>\n<li>Full-Time position(s) available.</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"Digital Marketing Associate\",\"meta_description\":\"Digital Marketing Associate\",\"meta_keywords\":\"Digital Marketing Associate\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 3,
                "title" => "Multimedia/Creatives Interns",
                "slug" => "multimediacreatives-interns",
                "department" => "Creatives",
                "experience" => "0",
                "banner" => "multimediacreatives-interns-60c74fc01cf0c.png",
                "overview" => "<ul>\n<li>Review and understand client&rsquo;s creative briefs.</li>\n<li>Create creative and modern designs for web, mobile, applications and other online applications</li>\n<li>Communicate with clients for design pitch and modification</li>\n<li>Work with a team of designers, developers and marketing staff</li>\n<li>Research the latest trends in web designs and graphic arts</li>\n<li>Help the assigned department to the task given to them</li>\n<li>Do the pending work of the department</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree in Multimedia Arts/Fine Arts, Advertising Arts, Graphic Artist/Motion Graphic Artist, Animator or equivalent.</li>\n<li>Can render at a minimum of 300 hours.</li>\n<li>No. of required hours (at least 8 hours maximum for a day)</li>\n<li>Internship program will be strictly on a Work-From-Home/Virtual Arrangement. Given the nature of the internship it is required for the applicant to have his/her own workstation (Laptop/PC and a&nbsp;<span class=\"il\">stable</span>&nbsp;<span class=\"il\">internet</span>&nbsp;<span class=\"il\">connection</span>).</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"Multimedia\\/Creatives Interns\",\"meta_description\":\"Multimedia\\/Creatives Interns\",\"meta_keywords\":\"Multimedia\\/Creatives Interns\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 4,
                "title" => "Marketing Interns",
                "slug" => "marketing-interns",
                "department" => "Marketing",
                "experience" => "0",
                "banner" => "marketing-interns-60c74fe20a6f0.png",
                "overview" => "<ul>\n<li>Content Writing</li>\n<li>Responsible for the development of customers' digital marketing pitch and plan</li>\n<li>Coordinates with sales, creatives, and development teams regarding customer's project updates and customer's digital presence analytics</li>\n<li>Monitors clients&rsquo; digital presence and online reputation</li>\n<li>Monitors competitors&rsquo; activity</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree in Marketing, Advertising or equivalent.</li>\n<li>Can render at a minimum of 300 hours.</li>\n<li>No. of required hours (at least 8 hours maximum for a day)</li>\n<li>Internship program will be strictly on a Work-From-Home/Virtual Arrangement. Given the nature of the internship it is required for the applicant to have his/her own workstation (Laptop/PC and a&nbsp;<span class=\"il\">stable</span>&nbsp;<span class=\"il\">internet</span>&nbsp;<span class=\"il\">connection</span>).</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"Marketing Interns\",\"meta_description\":\"Marketing Interns\",\"meta_keywords\":\"Marketing Interns\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 5,
                "title" => "IT/Quality Assurance Interns",
                "slug" => "itquality-assurance-interns",
                "department" => "Development",
                "experience" => "0",
                "banner" => "itweb-and-mobile-app-development-interns-60c75770cd3dc.png",
                "overview" => "<ul>\n<li>Designing, coding, and modifying websites, from layout to function</li>\n<li>Create visually appealing site</li>\n<li>Programming of IT projects</li>\n<li>Website development</li>\n<li>Database management</li>\n<li>Help the assigned department to the task given to them</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree in IT/Computer Engineering, Computer Science, Computer Programming/Quality Assurance or equivalent.</li>\n<li>Can render at a minimum of 300 hours.</li>\n<li>No. of required hours (at least 8 hours maximum for a day)</li>\n<li>Internship program will be strictly on a Work-From-Home/Virtual Arrangement. Given the nature of the internship it is required for the applicant to have his/her own workstation (Laptop/PC and a&nbsp;<span class=\"il\">stable</span>&nbsp;<span class=\"il\">internet</span>&nbsp;<span class=\"il\">connection</span>).</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"IT\\/Quality Assurance Interns\",\"meta_description\":\"IT\\/Quality Assurance Interns\",\"meta_keywords\":\"IT\\/Quality Assurance Interns\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 6,
                "title" => "Web Developer (JR.)",
                "slug" => "web-developer-jr",
                "department" => "Development",
                "experience" => "1",
                "banner" => "web-developer-jr-60d069a707b38.png",
                "overview" => "<ul>\n<li>Defines website/application objectives by analyzing user requirements; envisioning system features and functionality.</li>\n<li>Designs and develops user interfaces by setting expectations and features priorities throughout development life cycle; determining design methodologies and tool sets; completing programming using languages and software products; designing and conducting tests.</li>\n<li>Recommends system solutions by comparing advantages and disadvantages of custom development and purchase alternatives.</li>\n<li>Integrates applications by designing database architecture and server scripting; studying and establishing connectivity with network systems, search engines, and information servers.</li>\n<li>Complete project development by coordinating requirements, schedules, and activities; contributing to team/client meetings; troubleshooting development and production problems across multiple environments and operating platforms.</li>\n<li>Supports users by developing documentation and assistance tools.</li>\n<li>Updates job knowledge by researching new Web technologies and software products; participating in educational opportunities; reading professional publications; maintaining personal networks; participating in professional organizations.</li>\n<li>Enhances organization reputation by accepting ownership for accomplishing new and different requests; exploring opportunities to add value to job accomplishments.</li>\n<li>Supports and develops Junior Web Application developers by providing advice and coaching</li>\n</ul>",
                "requirements" => "<ul>\n<li>Graduate of BS Information Technology, Computer Science, or Computer Engineering.</li>\n<li>Deep experience in object-oriented PHP programming and MVC frameworks such as Laravel or CodeIgniter</li>\n<li>Understanding of best practices for creating and securing RESTful APIs</li>\n<li>Strong knowledge of front-end technologies, such as JavaScript, HTML5, and CSS3</li>\n<li>Understanding of common exploits such as SQL injection, XSS, etc.</li>\n<li>Knowledge of fundamental design principles behind a scalable application</li>\n<li>Experience with MySQL and Familiarity with NoSQL databases such as Mongo and Redis is a plus</li>\n<li>Experience creating database schemas that represent and support business processes</li>\n<li>Proficient understanding of code versioning tools, such as Git</li>\n<li>Knowledge in Web Server installation and implementation</li>\n<li>Experience in using Centos/Redhat and CPanel/WHM</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"Web Developer (JR.)\",\"meta_description\":\"Web Developer (JR.)\",\"meta_keywords\":\"Web Developer (JR.)\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 7,
                "title" => "Data Analyst (Statistician)",
                "slug" => "data-analyst-statistician",
                "department" => "null",
                "experience" => "1",
                "banner" => "data-analyst-statistician-60d441e98f7cc.png",
                "overview" => "<ul>\n<li>Process and collate data, figures, and other significant statistics</li>\n<li>Interpret results using statistical and analytical tools</li>\n<li>Analyze data and results with utmost accuracy</li>\n<li>Provide detailed and technical statistical reports</li>\n<li>Translate numbers and figures into a comprehensive yet easy-to-understand text</li>\n<li>Liaise with the Marketing and Sales Departments</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree in Statistics or Mathematics.</li>\n<li>Preferably with at least 1 year of working experience in the related field is required for this position.</li>\n<li>With excellent Numerical and Analytical skill.</li>\n<li>With excellent communication skills.</li>\n<li>Must be Result-oriented professional.</li>\n<li>Applicants must be willing to work in Makati City.</li>\n</ul>",
                "status" => 0,
                "seo" => "{\"meta_title\":\"Data Analyst (Statistician)\",\"meta_description\":\"Data Analyst (Statistician)\",\"meta_keywords\":\"Data Analyst (Statistician)\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 8,
                "title" => "Business Development Specialist",
                "slug" => "business-development-specialist",
                "department" => "Brands",
                "experience" => "1",
                "banner" => "business-development-specialist-60d44202776b5.png",
                "overview" => "<ul>\n<li>Identifying new sales leads</li>\n<li>Account management role</li>\n<li>Pitching products and/or services</li>\n<li>Maintaining good relationships with existing customers</li>\n<li>Researching organisations to identify new leads and potential new markets</li>\n<li>Contacting potential clients via email or phone to establish rapport and set up meetings</li>\n<li>Attending conferences, meetings, and industry events</li>\n<li>Contacting clients to inform them about new developments in the company&rsquo;s products</li>\n<li>Developing quotes and proposals</li>\n<li>Negotiating and renegotiating by phone, email, and in person</li>\n<li>Developing sales goals for the team and ensuring they are met</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree, any field.</li>\n<li>Preferably 1-4 Yrs Experienced Employees specializing in Sales - Corporate or equivalent.</li>\n<li>At least 1 year(s) of working experience in the related field is required for this position.</li>\n<li>Applicants must be willing to work in Makati.</li>\n<li>Full-Time position(s) available.</li>\n<li>This post is for MORNING SHIFT and FULL- TIME EMPLOYMENT. Compensation package, commission, and incentive will be discussed during the processing.</li>\n</ul>",
                "status" => 0,
                "seo" => "{\"meta_title\":\"Business Development Specialist\",\"meta_description\":\"Business Development Specialist\",\"meta_keywords\":\"Business Development Specialist\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 9,
                "title" => "Freelance Thai Speaker",
                "slug" => "freelance-thai-speaker",
                "department" => NULL,
                "experience" => NULL,
                "banner" => NULL,
                "overview" => "<ul>\n<li>Content Creation and Edit</li>\n<li>Adding of Local Content/Text in Image</li>\n<li>Copywriting of post Caption</li>\n<li>Grammar Checking of Post and Image Caption</li>\n<li>Checking of Cultural, social and political sensitivity of posted content</li>\n<li>At least 4 posts per month</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a High School Diploma, Vocational Diploma / Short Course Certificate, Bachelor's/College Degree , any field.</li>\n<li>Applicants must be willing to work in Makati City.</li>\n<li>Preferably with basic knowledge in Photoshop</li>\n<li>No work experience required as long as well-versed in Thai language.</li>\n<li>2 position(s) available.</li>\n</ul>",
                "status" => 0,
                "seo" => "{\"meta_title\":\"Freelance Thai Speaker\",\"meta_description\":\"Freelance Thai Speaker\",\"meta_keywords\":\"Freelance Thai Speaker\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 10,
                "title" => "Freelance Bahasa-Malaysia Speaker",
                "slug" => "freelance-bahasa-malaysia-speaker",
                "department" => NULL,
                "experience" => NULL,
                "banner" => NULL,
                "overview" => "<ul>\n<li>Content Creation and Edit</li>\n<li>Adding of Local Content/Text in Image</li>\n<li>Copywriting of post caption</li>\n<li>Grammar Checking of Post and Image Caption</li>\n<li>Checking of Cultural, social and political sensitivity of posted content</li>\n<li>At At least 4 posts per month</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a High School Diploma, Vocational Diploma / Short Course Certificate, Bachelor's/College Degree , any field.</li>\n<li>Applicants must be willing to work in Makati City.</li>\n<li>Preferably with basic knowledge in Photoshop</li>\n<li>No work experience required as long as well-versed in Malay (Bahasa-Malaysia) language.</li>\n<li>2 position(s) available.</li>\n</ul>",
                "status" => 0,
                "seo" => "{\"meta_title\":\"Freelance Bahasa-Malaysia Speaker\",\"meta_description\":\"Freelance Bahasa-Malaysia Speaker\",\"meta_keywords\":\"Freelance Bahasa-Malaysia Speaker\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 11,
                "title" => "Freelance Lao Speaker",
                "slug" => "freelance-lao-speaker",
                "department" => NULL,
                "experience" => NULL,
                "banner" => NULL,
                "overview" => "<ul>\n<li>Content Creation and Edit</li>\n<li>Adding of Local Content/Text in Image</li>\n<li>Copywriting of post caption</li>\n<li>Grammar Checking of Post and Image Caption</li>\n<li>Checking of Cultural, social and political sensitivity of posted content</li>\n<li>At least 4 posts per month</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a High School Diploma, Vocational Diploma / Short Course Certificate, Bachelor's/College Degree , any field.</li>\n<li>Applicants must be willing to work in Makati City.</li>\n<li>Preferably with basic knowledge in Photoshop</li>\n<li>No work experience required as long as well-versed in Lao language.</li>\n<li>2 position(s) available.</li>\n</ul>",
                "status" => 0,
                "seo" => "{\"meta_title\":\"Freelance Lao Speaker\",\"meta_description\":\"Freelance Lao Speaker\",\"meta_keywords\":\"Freelance Lao Speaker\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 12,
                "title" => "Freelance Khmer (Cambodian) Speaker",
                "slug" => "freelance-khmer-cambodian-speaker",
                "department" => NULL,
                "experience" => NULL,
                "banner" => NULL,
                "overview" => "<ul>\n<li>Content Creation and Edit</li>\n<li>Adding of Local Content/Text in Image</li>\n<li>Copywriting of post caption</li>\n<li>Grammar Checking of Post and Image Caption</li>\n<li>Checking of Cultural, social and political sensitivity of posted content</li>\n<li>At least 4 posts per month</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a High School Diploma, Vocational Diploma / Short Course Certificate, Bachelor's/College Degree , any field.</li>\n<li>Applicants must be willing to work in Makati City.</li>\n<li>Preferably with basic knowledge in Photoshop</li>\n<li>No work experience required as long as well-versed in Cambodian language.</li>\n<li>2 position(s) available.</li>\n</ul>",
                "status" => 0,
                "seo" => "{\"meta_title\":\"Freelance Khmer (Cambodian) Speaker\",\"meta_description\":\"Freelance Khmer (Cambodian) Speaker\",\"meta_keywords\":\"Freelance Khmer (Cambodian) Speaker\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 13,
                "title" => "SEO Specialist - Work from Home",
                "slug" => "seo-specialist-work-from-home",
                "department" => "Marketing",
                "experience" => "1",
                "banner" => "seo-specialist-work-from-home-60d069ee4f735.png",
                "overview" => "<ul>\n<li>Execute tests, collect and analyze data and results, identify trends and insights in order to achieve maximum ROI in paid search campaigns</li>\n<li>Track, report, and analyze website analytics and PPC initiatives and campaigns</li>\n<li>Manage campaign expenses, staying on budget, estimating monthly costs and reconciling discrepancies.</li>\n<li>Optimize copy and landing pages for search engine marketing</li>\n<li>Perform ongoing keyword discovery, expansion and optimization</li>\n<li>Research and implement search engine optimization recommendations</li>\n<li>Research and analyze competitor websites</li>\n<li>Develop and implement link building strategy by having a solid grasp of how blogging, press releases, social media, and related strategies go hand-in-hand with SEO</li>\n<li>Work with the development team to ensure SEO best practices are properly implemented on newly developed code</li>\n<li>Work with editorial and marketing teams to drive SEO in content creation and content programming</li>\n<li>Recommend changes to website architecture, content, linking and other factors to improve SEO positions for target keywords.</li>\n<li>A functional understanding of HTML and CSS</li>\n<li>The ability to deploy an effective local and long-tail search strategy</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree, Computer Science/Information Technology, Business Studies/Administration/Management, Marketing or equivalent.</li>\n<li>At least 1 year(s) of experience both in Search Engine Marketing, and On-page and Off-page Search Engine Optimization.</li>\n<li>Applicants must be willing to work in Makati.</li>\n<li>Preferably 1-4 Yrs Experienced Employees specializing in IT/Computer - Software or equivalent.</li>\n<li>Experience with content writing, building backlinks, and optimizing webpages</li>\n<li>In-depth understanding of how local search works and best practices</li>\n<li>Great overall research and analytics skills</li>\n<li>Proven SEM experience managing PPC campaigns across Google, Yahoo and Bing</li>\n<li>In-depth experience with Google Analytics tool</li>\n<li>In depth knowledge in different SEO tools.</li>\n<li>Experience in using MOZ is an advantage.</li>\n<li>In depth understanding of ranking factors and search engine algorithms</li>\n<li>Experience in creating SEO plan.</li>\n<li>Excellent verbal and written communication skills</li>\n<li>Candidate must be available to start as soon as possible</li>\n<li>1 Full-Time position available</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"SEO Specialist\",\"meta_description\":\"SEO, Search engine\",\"meta_keywords\":\"Search Engine Optimization, SEO\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 14,
                "title" => "Graphic Designer (Illustrator) - Freelance",
                "slug" => "graphic-designer-illustrator-freelance",
                "department" => "Creatives",
                "experience" => "1",
                "banner" => "graphic-designer-illustrator-freelance-60d0687f0bf7d.png",
                "overview" => "<ul>\n<li>Review and understand internal and clients&rsquo; creative briefs.</li>\n<li>Create creative and modern designs for mobile games and applications.</li>\n<li>Communicate with the department for design pitch and modification.</li>\n<li>Work with a team of designers and developers.</li>\n<li>Research the latest trends in web designs and graphic arts.</li>\n<li>Ability to work under pressure and tight schedules and deadlines.</li>\n</ul>",
                "requirements" => "<ul>\n<li>Proven graphic designing experience for at least 1 year</li>\n<li>Must be savvy in Adobe Illustrator.</li>\n<li>Knowledge in Adobe Photoshop, After Effects, 3D Software and Adobe Creative suite is an advantage</li>\n<li>Possession of creative flair, versatility, conceptual/visual ability and originality</li>\n<li>Demonstrable graphic design skills with a strong portfolio</li>\n<li>Ability to interact, communicate and present ideas</li>\n<li>Highly proficient in all design aspects</li>\n<li>Professionalism regarding time, costs and deadlines</li>\n<li>Amenable to work in Ayala, Makati once pandemic is over.</li>\n<li>Can start as soon as possible</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"Graphic Designer, Graphic Artist\",\"meta_description\":\"Graphic Designing, Creatives\",\"meta_keywords\":\"Adobe Illustrator\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 15,
                "title" => "Content Writer - Work from Home",
                "slug" => "content-writer-work-from-home",
                "department" => "Marketing",
                "experience" => "1",
                "banner" => "content-writer-work-from-home-60d4422cf249c.png",
                "overview" => "<ul>\n<li>Responsible for the development of customers' digital marketing plans including but not limited to contents.</li>\n<li>Copywriting and content creation.</li>\n<li>Handles a minimum of 5 client accounts.</li>\n<li>Coordinates with sales, creative, and development teams regarding customer's project updates and customer's digital presence analytics.</li>\n<li>Monitors clients&rsquo; digital presence and online reputation</li>\n<li>Monitors competitors&rsquo; activity.</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree , Advertising/Media, Journalism, Business Studies/Administration/Management, Mass Communications, Marketing or equivalent.</li>\n<li>At least 1 year(s) of working experience in the related field is required for this position.</li>\n<li>Applicants must be willing to work in Makati City.</li>\n<li>Preferably 1-4 Yrs Experienced Employees specializing in Journalist/Editor or equivalent.</li>\n<li>2 Full-Time position(s) available.</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"Content Writer, Copywriting\",\"meta_description\":\"Copywriting, Blogs, Writing, Journalism\",\"meta_keywords\":\"Content Writing, Copywriting, Digital Marketing\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 16,
                "title" => "Communications & Journalism Internship",
                "slug" => "communications-journalism-internship",
                "department" => "Brands",
                "experience" => "0",
                "banner" => "communications-journalism-internship-60c750161ac4a.png",
                "overview" => "<ul>\n<li>Copywriting and content creation.</li>\n<li>Data Gathering: Prepare research instruments and conduct data gathering (FGD / surveys, etc.) with Data Analyst to make descriptive and inferential interpretations of the data.</li>\n<li>Helping create style guides or suggesting changes to ensure content is consistent and clear.</li>\n<li>Conducting research on any given topic and producing well-researched content for social media and websites.</li>\n<li>Will work and directly report to the Brands Department of PurpleBug Inc.</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree , Advertising/Media, Journalism, Business Studies/Mass Communications or equivalent.</li>\n<li>Can render at a minimum of 300 hours.</li>\n<li>No. of required hours (at least 8 hours maximum for a day)</li>\n<li>Internship program will be strictly on a Work-From-Home/Virtual Arrangement. Given the nature of the internship it is required for the applicant to have his/her own workstation (Laptop/PC and a&nbsp;<span class=\"il\">stable</span>&nbsp;<span class=\"il\">internet</span>&nbsp;<span class=\"il\">connection</span>).</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"Journalism\",\"meta_description\":\"Advertising\\/Media\",\"meta_keywords\":\"Mass Communications\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 17,
                "title" => "Digital Marketing Manager- Work from Home",
                "slug" => "digital-marketing-manager-work-from-home",
                "department" => "Marketing",
                "experience" => "5",
                "banner" => "digital-marketing-manager-work-from-home-60d06843e6c8b.png",
                "overview" => "<p><strong>Job Description:</strong></p>\n<ul>\n<li>Oversee Marketing Team's activities (Deliverables, Deadlines, Client Requests, etc.)</li>\n<li>Responsible for the development of customers' digital marketing plans.</li>\n<li>Monitors customers' ad placement.&nbsp;</li>\n<li>Monitors competitors&rsquo; activity.</li>\n<li>Process Monitoring</li>\n<li>Coordinates with sales, creative, and development teams regarding customer's project updates and customer's digital presence analytics.</li>\n<li>Monitors clients&rsquo; digital presence and online reputation</li>\n<li>Formulation of Marketing Strategies and Planning (Campaign production)</li>\n<li>Customer Engagement and Presentation</li>\n<li>Attending Operations Meeting and Strategic Planning annually.</li>\n</ul>",
                "requirements" => "<p><strong>Qualifications:</strong></p>\n<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree, Art/Design/Creative Multimedia, Advertising/Media, Business Studies/Administration/Management, Mass Communications, Marketing or equivalent.</li>\n<li>At least 5 years of working experience in the related field is required for this position.</li>\n<li>Candidate must have 3 years of supervisory or managerial experience.</li>\n<li>Can start as soon as possible.</li>\n<li>Applicants must be willing to work in Ayala, Makati City.</li>\n<li>Preferably Supervisor / 5 Yrs &amp; Up Experienced Employees specializing in Digital Marketing or equivalent.</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"Digital Marketing Manager, Digital\",\"meta_description\":\"Digital Marketing, Digital, Manager, Career Opportunities, Career, Job, Work from Home, Remote\",\"meta_keywords\":\"Digital Marketing, Digital, Manager, Career Opportunities, Career, Job, Work from Home, Remote\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 18,
                "title" => "IT Internship",
                "slug" => "it-internship",
                "department" => "Development",
                "experience" => "0",
                "banner" => NULL,
                "overview" => "<ul>\n<li>Create a modern designs for web, mobile, applications and other online applications.</li>\n<li>Work with a team of programmers, developers and quality assurance staff.</li>\n<li>Database Management</li>\n<li>Programming</li>\n<li>Help the assigned department to the task given to them.</li>\n<li>Do the pending work of the department.</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree in IT/Computer Engineering, Computer Science, Computer Programming/Quality Assurance or equivalent.</li>\n<li>Can render at a minimum of 300 hours.</li>\n<li>No. of required hours (at least 8 hours minimum for a day)</li>\n<li>Amenable to work in Ayala, Makati.</li>\n<li>Internship program will be strictly on a Work-From-Home/Virtual Arrangement. Given the nature of the internship it is required for the applicant to have his/her own workstation (Laptop/PC and a&nbsp;<span class=\"il\">stable</span>&nbsp;<span class=\"il\">internet</span>&nbsp;<span class=\"il\">connection</span>).</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"IT Internship\",\"meta_description\":\"IT Internship\",\"meta_keywords\":\"IT Internship\"}",
                "deleted_at" => "2021-06-15 02:19:48",
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 19,
                "title" => "WordPress Developer",
                "slug" => "wordpress-developer",
                "department" => "Development",
                "experience" => "1",
                "banner" => "wordpress-developer-60d06a6fa7a44.png",
                "overview" => "<p><strong>Job Description</strong></p>\n<ul>\n<li>Defines website/application objectives by analyzing user requirements; envisioning system features and functionality.</li>\n<li>Designs and develops user interfaces by setting expectations and features priorities throughout the development life cycle; determining design methodologies and toolsets; completing programming using languages and software products; designing and conducting tests.</li>\n<li>Complete project development by coordinating requirements, schedules, and activities; contributing to team/client meetings; troubleshooting development and production problems across multiple environments and operating platforms.</li>\n<li>Supports users by developing documentation and assistance tools.</li>\n</ul>\n<p>&nbsp;</p>",
                "requirements" => "<p><strong>Qualifications:</strong></p>\n<ul>\n<li>Graduate of Bachelor's Degree in Information Technology/Computer Science, and other related courses.</li>\n<li>With at least 1 year background in WordPress coding.</li>\n<li>Knowledge of existing&nbsp;WordPress</li>\n<li>Strong coding experience in web and application development using PHP, HTML5, CSS3, and JavaScript, required.</li>\n<li>WAMP/LAMP experience</li>\n<li>PHP Development experience</li>\n<li>Must be able to understand how CSS changes impact style across platforms and browsers.</li>\n<li>Can convert wireframes and comprehensive designs into code.</li>\n<li>Previous experience customizing WordPress to support specific functionality</li>\n<li>Create functionality written to conform to WordPress coding standards.</li>\n<li>Understanding of PHP back-end development.</li>\n<li>Knowledge of how to interact with RESTful APIs and formats (JSON, XML).</li>\n<li>Proficient understanding of code versioning tools.</li>\n<li>Ability to work in a high-energy, collaborative, team-oriented environment. Must be a team player.</li>\n<li>Knowledgeable with Wordpress E-commerce Ex. Woo or other E-Commerce plugins</li>\n</ul>\n<p>&nbsp;</p>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"Wordpress, Career Opportunity, Development,\",\"meta_description\":\"Wordpress, IT, Web development, PHP\",\"meta_keywords\":\"Wordpress, IT, Web development, PHP\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 20,
                "title" => "Web Developer (SR.)",
                "slug" => "web-developer-sr",
                "department" => "Development",
                "experience" => "2",
                "banner" => "web-developer-sr.png",
                "overview" => "<ul>\n<li>Defines website/application objectives by analyzing user requirements; envisioning system features and functionality.</li>\n<li>Designs and develops user interfaces by setting expectations and features priorities throughout development life cycle; determining design methodologies and tool sets; completing programming using languages and software products; designing and conducting tests.</li>\n<li>Recommends system solutions by comparing advantages and disadvantages of custom development and purchase alternatives.</li>\n<li>Integrates applications by designing database architecture and server scripting; studying and establishing connectivity with network systems, search engines, and information servers.</li>\n<li>Complete project development by coordinating requirements, schedules, and activities; contributing to team/client meetings; troubleshooting development and production problems across multiple environments and operating platforms.</li>\n<li>Supports users by developing documentation and assistance tools.</li>\n<li>Updates job knowledge by researching new Web technologies and software products; participating in educational opportunities; reading professional publications; maintaining personal networks; participating in professional organizations.</li>\n<li>Enhances organization reputation by accepting ownership for accomplishing new and different requests; exploring opportunities to add value to job accomplishments.</li>\n<li>Supports and develops Junior Web Application developers by providing advice and coaching</li>\n</ul>",
                "requirements" => "<ul>\n<li>Graduate of BS Information Technology, Computer Science, or Computer Engineering.</li>\n<li>Deep experience in object-oriented PHP programming and MVC frameworks such as Laravel or CodeIgniter</li>\n<li>Understanding of best practices for creating and securing RESTful APIs</li>\n<li>Strong knowledge of front-end technologies, such as JavaScript, HTML5, and CSS3</li>\n<li>Understanding of common exploits such as SQL injection, XSS, etc.</li>\n<li>Knowledge of fundamental design principles behind a scalable application</li>\n<li>Experience with MySQL and Familiarity with NoSQL databases such as Mongo and Redis is a plus</li>\n<li>Experience creating database schemas that represent and support business processes</li>\n<li>Proficient understanding of code versioning tools, such as Git</li>\n<li>Knowledge in Web Server installation and implementation</li>\n<li>Experience in using Centos/Redhat and CPanel/WHM</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"Web Developer (SR.)\",\"meta_description\":\"Web Developer (SR.)\",\"meta_keywords\":\"Web Developer (SR.)\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 21,
                "title" => "Freelance SEO Specialist",
                "slug" => "freelance-seo-specialist",
                "department" => "Marketing",
                "experience" => "1",
                "banner" => "freelance-seo-specialist-60eac8fbaca44.png",
                "overview" => "<ul>\n<li>Execute tests, collect and analyze data and results, identify trends and insights in order to achieve maximum ROI in paid search campaigns</li>\n<li>Track, report, and analyze website analytics and PPC initiatives and campaigns</li>\n<li>Manage campaign expenses, staying on budget, estimating monthly costs and reconciling discrepancies.</li>\n<li>Optimize copy and landing pages for search engine marketing</li>\n<li>Perform ongoing keyword discovery, expansion and optimization</li>\n<li>Research and implement search engine optimization recommendations</li>\n<li>Research and analyze competitor websites</li>\n<li>Develop and implement link building strategy by having a solid grasp of how blogging, press releases, social media, and related strategies go hand-in-hand with SEO</li>\n<li>Work with the development team to ensure SEO best practices are properly implemented on newly developed code</li>\n<li>Work with editorial and marketing teams to drive SEO in content creation and content programming</li>\n<li>Recommend changes to website architecture, content, linking and other factors to improve SEO positions for target keywords.</li>\n<li>A functional understanding of HTML and CSS</li>\n<li>The ability to deploy an effective local and long-tail search strategy</li>\n</ul>",
                "requirements" => "<ul>\n<li>Candidate must possess at least a Bachelor's/College Degree , Computer Science/Information Technology, Business Studies/Administration/Management, Marketing or equivalent.</li>\n<li>At least 1 year(s) of experience both in Search Engine Marketing, and On-page and Off-page Search Engine Optimization.</li>\n<li>Applicants must be willing to work in Makati.</li>\n<li>Preferably 1-4 Yrs Experienced Employees specializing in IT/Computer - Software or equivalent.</li>\n<li>Experience with content writing, building backlinks, and optimizing webpages</li>\n<li>In-depth understanding of how local search works and best practices</li>\n<li>Great overall research and analytics skills</li>\n<li>Proven SEM experience managing PPC campaigns across Google, Yahoo and Bing</li>\n<li>In-depth experience with Google Analytics tool</li>\n<li>In depth knowledge in different SEO tools.</li>\n<li>Experience in using MOZ is an advantage.</li>\n<li>In depth understanding of ranking factors and search engine algorithms</li>\n<li>Experience in creating SEO plan.</li>\n<li>Excellent verbal and written communication skills</li>\n<li>Candidate must be available to start as soon as possible</li>\n<li>1 Full-Time position available</li>\n</ul>",
                "status" => 1,
                "seo" => "{\"meta_title\":\"SEO Specialist, Freelance SEO\",\"meta_description\":\"SEO, Freelance, Digital Marketing, Digital\",\"meta_keywords\":\"SEO, Freelance, Digital Marketing, Digital\"}",
                "deleted_at" => NULL,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
        );

        Career::insert($careers);
    }
}
