<?php

use App\Content;
use Illuminate\Database\Seeder;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $contents = array(
            array(
                "id" => 1,
                "page" => "homepage",
                "section" => "banners",
                "body" => NULL,
                "contents" => "[{\"id\":\"123njkj\",\"body\":\"<p>Let PurpleBug lead your business to recovery this year.<\\/p>\",\"heading\":\"YOUR ROAD TO RECOVERY BEGINS HERE, TODAY!\",\"btn_link\":\"https:\\/\\/purplebug.net\\/services\",\"btn_label\":\"Inquire Now\",\"image\":\"your_road_to_recovery_starts_here.jpg\"},{\"heading\":\"EXPLORE YOUR DIGITAL OPTIONS.\",\"body\":\"<p>Achieve your business goals with effective online marketing solutions.<\\/p>\",\"btn_label\":\"Inquire Now\",\"btn_link\":\"https:\\/\\/purplebug.net\\/services\",\"id\":\"261aiaftl\",\"image\":\"explore_your_digital_options.jpg\"},{\"heading\":\"NAVIGATE \\nTHE DIGITAL WORLD.\",\"body\":\"<p>Drive through the digital journey with confidence.<\\/p>\",\"btn_label\":\"Inquire Now\",\"btn_link\":\"https:\\/\\/purplebug.net\\/services\",\"id\":\"6teh2io8q\",\"image\":\"navigate_the_digital_world.jpg\"},{\"heading\":\"REACH YOUR DESTINATION.\",\"body\":\"<p>Reach greater heights and achieve success with strategies that work.&nbsp;<\\/p>\",\"btn_label\":\"Inquire Now\",\"btn_link\":\"https:\\/\\/purplebug.net\\/services\",\"id\":\"k1tua92nw\",\"image\":\"reach_your_destination.jpg\"}]",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 2,
                "page" => "homepage",
                "section" => "partners",
                "body" => "<p>WE LOVE OUR CLIENTS<br />PurpleBug has been of service to a wide array of clients from different industries. Here&rsquo;s a list of our amazing clients that allowed PurpleBug to showcase its line of quality digital marketing solutions and online marketing services.</p>",
                "contents" => NULL,
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 3,
                "page" => "homepage",
                "section" => "footer_banner",
                "body" => NULL,
                "contents" => "{\"body\":\"<p>PurpleBug is a digital marketing agency in the Philippines that offers 360 degrees digital marketing solutions and online marketing services such as web design and web development services.<\\/p>\\n<p>Aside from these web solutions, PurpleBug also caters to search engine optimization services, online advertising, social media management services, online PR media, application development services, and other digital marketing solutions your brand requires.<\\/p>\",\"link\":\"https:\\/\\/purplebug.net\\/about-us\",\"image\":\"16197543611617153323Why Purplebug new.jpg\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 4,
                "page" => "homepage",
                "section" => "seo",
                "body" => NULL,
                "contents" => "{\"meta_title\":\"Digital Marketing Agency in the Philippines | PurpleBug\",\"meta_description\":\"PurpleBug is a digital marketing agency in the Philippines that offers a list of digital marketing solutions such as web development services, online advertising, search engine optimization services, online pr media, application development services, social media management services, and more.\",\"meta_keyword\":\"Digital Marketing Agency in the Philippines,PurpleBug\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 5,
                "page" => "about",
                "section" => "banner",
                "body" => NULL,
                "contents" => "{\"body\":\"<p>As a full-service digital marketing agency, PurpleBug provides a holistic approach for any brand&rsquo;s digital marketing campaign needs.<\\/p>\",\"heading\":\"We Think and Talk Digital\",\"image\":\"about_About Us.jpg\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 6,
                "page" => "about",
                "section" => "our_approach",
                "body" => "<h5><span style=\"color: #843fa1;\">Objectives</span></h5>\n<ol>\n<li>To be the preferred digital marketing consultant and solutions provider of companies in the Philippines.</li>\n<li>To provide topnotch solutions in digital marketing including web and mobile development, and be of service to local and international businesses.</li>\n<li>To be the pioneer in the development and management of portals and applications that are valuable to both businesses and consumers.</li>\n</ol>\n<h5><span style=\"color: #843fa1;\">Mission</span></h5>\n<p>PurpleBug provides a combined solution of strategy and technology in digital marketing and business development. We help businesses excel in the digital world, maximize their on ground and online presence, and grow their business strategically.</p>\n<h5><span style=\"color: #843fa1;\">Vision</span></h5>\n<p>To be an innovative leader in providing digital marketing solutions and online marketing services to businesses in the Philippines and internationally.</p>",
                "contents" => NULL,
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 7,
                "page" => "about",
                "section" => "why_purplebug",
                "body" => "<h5><span style=\"color: #843fa1;\">We have the experience.</span></h5>\n<p>PurpleBug has been in the industry for more than a decade and has been of service to a wide array of clients from different industries. This competence equips us the knowledge on how to maximize one&rsquo;s local and online presence in the digital world with high quality digital marketing solutions and online marketing services.</p>\n<h5><span style=\"color: #843fa1;\">We are cost-effective.</span></h5>\n<p>As a full-service digital marketing agency, PurpleBug provides relevant, results-oriented, and cost-effective holistic approach for any brand&rsquo;s digital marketing campaign from web solutions and social media services to online advertising and online PR media.</p>\n<h5><span style=\"color: #843fa1;\">We have a wide-range of services.</span></h5>\n<p>PurpleBug is a digital marketing agency in the Philippines that offers 360 degrees digital marketing solutions and online marketing services such as web design services and web development services. Aside from these web solutions, PurpleBug also caters to search engine optimization services, online advertising, social media management services, online pr media, application development services, and other digital marketing solutions your brand will be requiring.</p>",
                "contents" => NULL,
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 8,
                "page" => "about",
                "section" => "seo",
                "body" => NULL,
                "contents" => "{\"meta_title\":\"About Us | Digital Marketing Agency | PurpleBug\",\"meta_description\":\"PurpleBug is a full service digital marketing agency that offers web development services, social media management services, online advertising, online pr media, search engine optimization services, email marketing services, application development services, and other digital marketing solutions.\",\"meta_keyword\":\"About Us,Digital Marketing Agency,PurpleBug\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 9,
                "page" => "services",
                "section" => "banner",
                "body" => NULL,
                "contents" => "{\"body\":\"<p>PurpleBug crafts relevant and effective digital marketing solutions to strengthen your business&rsquo; on ground and online presence.<\\/p>\",\"heading\":\"Digital Services\",\"image\":\"services_dIGITAL SERVICES.jpg\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 10,
                "page" => "services",
                "section" => "seo",
                "body" => NULL,
                "contents" => "{\"meta_title\":\"Digital Services | Digital Marketing Agency | PurpleBug\",\"meta_description\":\"PurpleBug's list of  digital marketing solutions and online marketing services consist of web design services, web development services, social media management services, search engine optimization services, online advertising, online pr media, application development services, and more.\",\"meta_keyword\":\"Digital Services,Digital Marketing Agency,PurpleBug\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 11,
                "page" => "blogs",
                "section" => "banner",
                "body" => NULL,
                "contents" => "{\"body\":\"<div>\\n<div>Get&nbsp;the&nbsp;latest&nbsp;digital&nbsp;marketing&nbsp;news&nbsp;and&nbsp;updates&nbsp;for&nbsp;your&nbsp;business.<\\/div>\\n<\\/div>\",\"heading\":\"Be in the Know.\",\"image\":\"blogs_Blogs banner.jpg\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 12,
                "page" => "blogs",
                "section" => "seo",
                "body" => NULL,
                "contents" => "{\"meta_title\":\"Blogs | Digital Marketing Agency | PurpleBug\",\"meta_description\":\"Be in the know! Get the Latest digital marketing news and updates.\",\"meta_keyword\":\"Blogs,Digital Marketing Agency,PurpleBug\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 13,
                "page" => "careers",
                "section" => "banner",
                "body" => NULL,
                "contents" => "{\"body\":\"<p>Passionate about digital marketing and technology? PurpleBug is the right place for you!<\\/p>\",\"heading\":\"Join Our Team\",\"image\":\"careers_Careers.jpg\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 14,
                "page" => "careers",
                "section" => "seo",
                "body" => NULL,
                "contents" => "{\"meta_title\":\"Careers | Digital Marketing Agency | PurpleBug\",\"meta_description\":\"As a full service digital marketing agency, PurpleBug requires a team of experts in the field of web development services, online advertising, search engine optimization services, online pr media, application development services, social media management services, and more.\",\"meta_keyword\":\"Careers,Digital Marketing Agency,PurpleBug\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 15,
                "page" => "teams",
                "section" => "banner",
                "body" => NULL,
                "contents" => "{\"body\":\"<div>\\n<div>PurpleBug&nbsp;is&nbsp;made&nbsp;up&nbsp;of&nbsp;exceptionally&nbsp;talented&nbsp;team&nbsp;of&nbsp;digital&nbsp;experts.<\\/div>\\n<\\/div>\",\"heading\":\"Meet the Team.\",\"image\":\"teams_Our Team banner.jpg\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 16,
                "page" => "teams",
                "section" => "who_we_are",
                "body" => "<p>Our team is made up of brilliant digital marketing experts, ready to help you build your solid online presence.</p>",
                "contents" => NULL,
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 17,
                "page" => "teams",
                "section" => "executives",
                "body" => NULL,
                "contents" => "[{\"body\":\"<p>A business development and marketing expert with a wide experience in dealing businesses in Asia for Telecommunication and IT products. Graduated from De La Salle University (Manila, Philippines) with a degree in the field of Advertising Management.<\\/p>\",\"name\":\"Marlon Gonzales\",\"position\":\"CEO and President\",\"image\":\"marlon_gonzales.jpg\"},{\"body\":\"<p>A licensed Electronics Communication Engineer (Technological Institute of the Philippines) with an MBA at University of Santo Tomas. An expert project manager for web, mobile applications and systems.<\\/p>\",\"name\":\"Jonnadeth Coja\",\"position\":\"COO\",\"image\":\"jonna_coja.jpg\"}]",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 18,
                "page" => "teams",
                "section" => "join_our_team",
                "body" => NULL,
                "contents" => "{\"body\":\"<p>We are passionate about digital marketing and technology. If you are too, PurpleBug is the right place for you!<\\/p>\",\"link\":\"https:\\/\\/purplebug.net\\/careers\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 19,
                "page" => "teams",
                "section" => "seo",
                "body" => NULL,
                "contents" => "{\"meta_title\":\"Our Team,Digital Marketing Agency,PurpleBug\",\"meta_description\":\"Our Teams\",\"meta_keyword\":\"Our Team,Digital Marketing Agency,PurpleBug\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 20,
                "page" => "contact",
                "section" => "banner",
                "body" => NULL,
                "contents" => "{\"body\":\"<p>Got questions? Get in touch with us!<\\/p>\",\"heading\":\"INQUIRE NOW\",\"image\":\"contact_Contact Us.jpg\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 21,
                "page" => "contact",
                "section" => "contact_details",
                "body" => NULL,
                "contents" => "[{\"id\": \"123njkj\", \"details\": [\"Unit 806, Antel 2000 Corporate Center, Valero St., Salcedo Village, Makati City, 1226, Philippines\"], \"heading\": \"Operation Address\"}, {\"id\": \"1m79g1x0s\", \"details\": [\"(02) 8-551-0986 (09:00-10:00 +8GMT)\", \"(02) 8-256-6714 (09:00-10:00 +8GMT)\"], \"heading\": \"Contact No.\"}, {\"id\": \"rifmmfydr\", \"details\": [\"inquiries@purplebugmail.net\"], \"heading\": \"Email Address\"}]",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 22,
                "page" => "contact",
                "section" => "seo",
                "body" => NULL,
                "contents" => "{\"meta_title\":\"Contact Us | Digital Marketing Agency | PurpleBug\",\"meta_description\":\"To know more about PurpleBug's digital marketing solutions and online marketing services, or if you want to join one of the best digital marketing agency in the country, feel free to contact or email us. In addition, don't hesitate to ask questions regarding our online advertising opportunities.\",\"meta_keyword\":\"Contact Us, Digital Marketing Agency, PurpleBug\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 23,
                "page" => "insights",
                "section" => "banner",
                "body" => NULL,
                "contents" => "{\"body\": null, \"image\": null, \"heading\": \"insights\"}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 24,
                "page" => "insights",
                "section" => "seo",
                "body" => NULL,
                "contents" => "{\"meta_title\": \"insights\", \"meta_keyword\": null, \"meta_description\": null}",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
        );

        Content::insert($contents);
    }
}
