<?php

use App\Partner;
use Illuminate\Database\Seeder;

class PartnerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $partners = array(
            array(
                "id" => 1,
                "image" => "604820a40bfd1acer.jpg",
                "alt_text" => "acer",
                "link" => "https://academy.acer.com.ph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 2,
                "image" => "604820a3f1368aj_research.jpg",
                "alt_text" => "aj-research",
                "link" => "https://www.ajrph.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 3,
                "image" => "604820a392f23angel.jpg",
                "alt_text" => "angel",
                "link" => "https://www.facebook.com/ILoveAngelMilk",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 4,
                "image" => "604820a48b922arya.jpg",
                "alt_text" => "arya",
                "link" => "http://www.aryaresidences.com.ph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 5,
                "image" => "604820a4dfe2darthaland.jpg",
                "alt_text" => "arthaland",
                "link" => "https://www.arthaland.com.ph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 6,
                "image" => "604820a55a975asia_massage.jpg",
                "alt_text" => "asia-massage",
                "link" => "https://asianmassageph.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 7,
                "image" => "604820a57e6a4atopiclair.jpg",
                "alt_text" => "atopiclair",
                "link" => "https://www.dermacaredirect.co.uk/atopiclair-cream-100ml.html",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 8,
                "image" => "604820a58b97cbayer.jpg",
                "alt_text" => "bayer",
                "link" => "https://www.facebook.com/BayerPhilippinesPetCare",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 9,
                "image" => "604820a605198bellavita.jpg",
                "alt_text" => "bellavita",
                "link" => "https://www.facebook.com/BellaVitaLandCorp",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 10,
                "image" => "604820a62282ebewell.jpg",
                "alt_text" => "bewell",
                "link" => "https://www.facebook.com/bewellcsodiumascorbate",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 11,
                "image" => "604820a662984bifiesta.jpg",
                "alt_text" => "bifiesta",
                "link" => "https://www.facebook.com/BifestaPhilippines",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 12,
                "image" => "604820a7eb83dbilaxten.jpg",
                "alt_text" => "bilaxten",
                "link" => "https://purplebug.net/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 13,
                "image" => "604820a863aa0blims.jpg",
                "alt_text" => "blims",
                "link" => "https://www.facebook.com/blimsfurniture",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 14,
                "image" => "604820a89292cbowwow.jpg",
                "alt_text" => "bowwow",
                "link" => "https://www.facebook.com/BowWowPH",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 15,
                "image" => "604820a8b17c2bulgogi_brothers.jpg",
                "alt_text" => "bulgogi-brothers",
                "link" => "https://www.facebook.com/Bulgogi.Brothers.Philippines",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 16,
                "image" => "604820a8daac7bpi.jpg",
                "alt_text" => "bpi",
                "link" => "https://www.bpi.com.ph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 17,
                "image" => "604820a8e0683california.jpg",
                "alt_text" => "california",
                "link" => "https://www.cpk.com.ph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 18,
                "image" => "604820a94ed27cardimax.jpg",
                "alt_text" => "cardimax",
                "link" => "http://cardimax.com.ph/?fbclid=IwAR3_6aIerehv0Pa7QvbgK1yJe3uwtpdaNPAJQ12k4n7RA83uICiAMjnr5b8",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 19,
                "image" => "604820aa027b4cccc.jpg",
                "alt_text" => "cccc",
                "link" => "https://climate.gov.ph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 20,
                "image" => "604820aa42367cetaphil.jpg",
                "alt_text" => "cetaphil",
                "link" => "https://www.facebook.com/CetaphilME",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 21,
                "image" => "604820aa87de7chekhup.jpg",
                "alt_text" => "chekhup",
                "link" => "https://www.facebook.com/chekhup.com.my",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 22,
                "image" => "604820aac80d0clinique.jpg",
                "alt_text" => "clinique",
                "link" => "https://www.clinique.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 23,
                "image" => "60482158e8954costa.jpg",
                "alt_text" => "costa",
                "link" => "https://www.costacruises.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 24,
                "image" => "6048215943d53dennis.jpg",
                "alt_text" => "dennis",
                "link" => "http://www.denniscoffeegarden.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 25,
                "image" => "60482159570e0crisdy_na.jpg",
                "alt_text" => "crisdy-na",
                "link" => "https://purplebug.net/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 26,
                "image" => "604821598c67adatem.jpg",
                "alt_text" => "datem",
                "link" => "https://www.datem.com.ph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 27,
                "image" => "60482159f325bdequadin.jpg",
                "alt_text" => "dequadin",
                "link" => "https://purplebug.net/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 28,
                "image" => "6048215a11bf0dermatix.jpg",
                "alt_text" => "dermatix",
                "link" => "https://dermatix.asia/our-scar-treatments/dermatix-ultra",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 29,
                "image" => "6048215aec352eastwest.jpg",
                "alt_text" => "eastwest",
                "link" => "https://www.eastwestbanker.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 30,
                "image" => "6048215b09710drypers.jpg",
                "alt_text" => "drypers",
                "link" => "https://www.facebook.com/DrypersPhilippines",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 31,
                "image" => "6048215b200a6lancaster.jpg",
                "alt_text" => "downtown-lancaster",
                "link" => "https://www.facebook.com/downtownlancastercavite/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 32,
                "image" => "6048215b85429emtrix.jpg",
                "alt_text" => "emtrix",
                "link" => "https://www.facebook.com/EmtrixMalaysia",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 33,
                "image" => "6048215b7eeaeentrego.jpg",
                "alt_text" => "entrego",
                "link" => "https://www.facebook.com/EntregoPH",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 34,
                "image" => "6048215bc2390fastum_gel.jpg",
                "alt_text" => "fastum-gel",
                "link" => "https://purplebug.net/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 35,
                "image" => "6048215c3d9c2ferring.jpg",
                "alt_text" => "ferring",
                "link" => "https://www.ferring.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 36,
                "image" => "6048215c714a6filinvest.jpg",
                "alt_text" => "filinvest",
                "link" => "https://filinvest.com/?fbclid=IwAR3TuIuxvM2hb9G66gwpWQXTTCysXmfFENeoL8-saREfG9hxKI6qFhMp77o",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 37,
                "image" => "6048263f7c3ddfor_me.jpg",
                "alt_text" => "for-me",
                "link" => "https://www.facebook.com/forme",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 38,
                "image" => "6048263fa3733forbes_estates.jpg",
                "alt_text" => "forbes-estates",
                "link" => "https://forbesestateslipa.weebly.com/?fbclid=IwAR32Tz5gFnhOWhkQ6KlKP_8rsvIgUpHKxDSEJlKkMybvw9NZzK4dKy74bSU",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 39,
                "image" => "6048264058dc1fiorgelato.jpg",
                "alt_text" => "fiorgelato",
                "link" => "https://www.fiorgelatointernational.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 40,
                "image" => "6048263fd74cbflanax.jpg",
                "alt_text" => "flanax",
                "link" => "https://www.facebook.com/FlanaxPhilippines/about/?ref=page_internal",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 41,
                "image" => "6048264089702gatsby.jpg",
                "alt_text" => "gatsby",
                "link" => "https://www.facebook.com/GatsbyPhilippines",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 42,
                "image" => "6048264079762fucidin.jpg",
                "alt_text" => "fucidin",
                "link" => "https://purplebug.net/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 43,
                "image" => "604826440a7c5genaro.jpg",
                "alt_text" => "genaro",
                "link" => "https://www.facebook.com/genarosbibingkaph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 44,
                "image" => "604826442afbehandy_man.jpg",
                "alt_text" => "handy-man",
                "link" => "https://handyman.com.ph/?fbclid=IwAR0sP88wW4OHDJSEJ52nUDV6pJiZNf5IwXWu7ins28mH6C4r_SLXwrikSpM",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 45,
                "image" => "6048264436076gly_derm.jpg",
                "alt_text" => "gly-derm",
                "link" => "https://www.facebook.com/glyderm0089",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 46,
                "image" => "60482644747b5hapee_kiddie.jpg",
                "alt_text" => "hapee-kiddie",
                "link" => "https://www.facebook.com/HapeeKiddie",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 47,
                "image" => "60482645097d8grand_monaco.jpg",
                "alt_text" => "grand-monaco",
                "link" => "https://www.facebook.com/grandmonacoph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 48,
                "image" => "6048264510301globe.jpg",
                "alt_text" => "globe",
                "link" => "https://www.facebook.com/globeph",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 49,
                "image" => "604826479cf24ihop.jpg",
                "alt_text" => "ihop",
                "link" => "https://www.ihop.com/en",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 50,
                "image" => "60482647c4804iremit.jpg",
                "alt_text" => "iremit",
                "link" => "http://www.iremit.at/home",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 51,
                "image" => "60482648ec117ilustrata.jpg",
                "alt_text" => "ilustrata",
                "link" => "https://www.facebook.com/OfficialIlustrataResidences",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 52,
                "image" => "60482649e1d0eiduno.jpg",
                "alt_text" => "heroine-make",
                "link" => "https://www.facebook.com/HeroineMakeSingapore",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 53,
                "image" => "6048264a09607hapee_baby.jpg",
                "alt_text" => "hapee-baby",
                "link" => "https://www.facebook.com/HapeeKiddie",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 54,
                "image" => "6048264a64fb2john_robert_powers.jpg",
                "alt_text" => "john-robert-powers",
                "link" => "https://www.facebook.com/JRPManila",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 55,
                "image" => "6048264b8728ekwell.jpg",
                "alt_text" => "kwell",
                "link" => "https://www.facebook.com/kwellph",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 56,
                "image" => "6048264ba337bkomodo.jpg",
                "alt_text" => "komodo",
                "link" => "https://www.facebook.com/KomodoArtcrafts",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 57,
                "image" => "6048264be1e57lancaster.jpg",
                "alt_text" => "lancaster",
                "link" => "https://www.lancasternewcity.com.ph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 58,
                "image" => "6048264e20df1landbank.jpg",
                "alt_text" => "landbank",
                "link" => "https://www.landbank.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 59,
                "image" => "6048264f06d5flandco.jpg",
                "alt_text" => "landco",
                "link" => "https://landco.ph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 60,
                "image" => "6048264f8e661lemon_square_power.jpg",
                "alt_text" => "lemon-square-power",
                "link" => "https://www.facebook.com/Powerpops/?ref=page_internal",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 61,
                "image" => "6048264fb7e71licealiz.jpg",
                "alt_text" => "licealiz",
                "link" => "https://www.facebook.com/licealiz",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 62,
                "image" => "6048264fbf63dlexus.jpg",
                "alt_text" => "lexus",
                "link" => "https://www.facebook.com/LexusManila",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 63,
                "image" => "604826500ef2alemon_square_krispy.jpg",
                "alt_text" => "lemon-square-krispy",
                "link" => "https://www.facebook.com/KrispyPuffsPH",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 64,
                "image" => "6048265208436locetar.jpg",
                "alt_text" => "locetar",
                "link" => "https://purplebug.net/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 65,
                "image" => "60482652e6860lucidol.jpg",
                "alt_text" => "lucidol",
                "link" => "https://www.facebook.com/LUCIDO.L.Thailand",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 66,
                "image" => "604826534127cmicara.jpg",
                "alt_text" => "micara",
                "link" => "https://micaraland.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 67,
                "image" => "6048265345dealoreal.jpg",
                "alt_text" => "loreal",
                "link" => "https://www.lorealparis.com.ph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 68,
                "image" => "60482653a6d41memo.jpg",
                "alt_text" => "memo",
                "link" => "https://memofashion.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 69,
                "image" => "604826553d74dmighty_mom.jpg",
                "alt_text" => "mighty-mom",
                "link" => "https://www.facebook.com/mightymom",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 70,
                "image" => "60482655f2034natrapharm.jpg",
                "alt_text" => "natrapharm",
                "link" => "https://www.natrapharm.com/index.html",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 71,
                "image" => "604826562135cmodern_shanghai.jpg",
                "alt_text" => "modern-shanghai",
                "link" => "https://www.facebook.com/ModernShanghaiPhilippines",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 72,
                "image" => "60482656f33d0ovaltine.jpg",
                "alt_text" => "ovaltine",
                "link" => "https://www.facebook.com/ovaltinephilippines",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 73,
                "image" => "604826576094coxygen.jpg",
                "alt_text" => "oxygen",
                "link" => "https://www.facebook.com/oxgnfashion",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 74,
                "image" => "6048265782073pearlie_white.jpg",
                "alt_text" => "pearlie-white",
                "link" => "https://www.facebook.com/pearliewhite",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 75,
                "image" => "6048265a01547pixy.jpg",
                "alt_text" => "pixy",
                "link" => "https://www.facebook.com/pixystyle/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 76,
                "image" => "6048265a50c34pro_friends.jpg",
                "alt_text" => "pro-friends",
                "link" => "https://www.profriends.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 77,
                "image" => "6048265a7fbdbperla.jpg",
                "alt_text" => "perla",
                "link" => "https://www.facebook.com/perlaphilippines",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 78,
                "image" => "6048265ab01dbregatta.jpg",
                "alt_text" => "regatta",
                "link" => "https://www.regattalifestyle.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 79,
                "image" => "6048265bc45e3robinson_appliances.jpg",
                "alt_text" => "robinson-appliances",
                "link" => "https://www.facebook.com/robinsonsappliances.ph",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 80,
                "image" => "6048265bc0775rustans.jpg",
                "alt_text" => "rustans",
                "link" => "https://www.facebook.com/rustansph",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 81,
                "image" => "6048265d9c60dsanofi.jpg",
                "alt_text" => "sanofi",
                "link" => "https://www.sanofi.ph/en",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 82,
                "image" => "6048265e79d00skybiz.jpg",
                "alt_text" => "skybiz",
                "link" => "https://www.facebook.com/skybizphilippines",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 83,
                "image" => "6048265f8dcd3scrool_rock.jpg",
                "alt_text" => "scrool-rock",
                "link" => "https://locations.schoolofrock.com/philippines",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 84,
                "image" => "60482660652efsuntech.jpg",
                "alt_text" => "suntech",
                "link" => "https://www.facebook.com/SuntechiPark/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 85,
                "image" => "60482660648e9sogo.jpg",
                "alt_text" => "sogo",
                "link" => "https://www.hotelsogo.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 86,
                "image" => "604826605e026sebclair.jpg",
                "alt_text" => "sebclair",
                "link" => "https://purplebug.net/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 87,
                "image" => "60482660be581thai.jpg",
                "alt_text" => "thai",
                "link" => "https://www.thaiairways.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 88,
                "image" => "60482661af26athesquare.jpg",
                "alt_text" => "thesquare",
                "link" => "https://purplebug.net/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 89,
                "image" => "6048266419b30true_value.jpg",
                "alt_text" => "true-value",
                "link" => "https://truevalue.com.ph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 90,
                "image" => "60482664744a3total.jpg",
                "alt_text" => "total",
                "link" => "https://www.facebook.com/TotalinthePhilippines",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 91,
                "image" => "60482664a8d69ucpb.jpg",
                "alt_text" => "ucpb",
                "link" => "https://www.ucpb.com/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 92,
                "image" => "6048266541f7etwinnings.jpg",
                "alt_text" => "twinnings",
                "link" => "https://www.facebook.com/TwiningsPhilippines",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 93,
                "image" => "60482665bff98urban_hive.jpg",
                "alt_text" => "urban-hive",
                "link" => "https://www.facebook.com/UrbanHiveP",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 94,
                "image" => "60482665c1345ultrapak.jpg",
                "alt_text" => "ultrapak",
                "link" => "https://www.facebook.com/ultrapakofficial/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 95,
                "image" => "604826672f39bveterans_bank.jpg",
                "alt_text" => "veterans-bank",
                "link" => "https://www.veteransbank.com.ph/",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 96,
                "image" => "604826677a219watami.jpg",
                "alt_text" => "watami",
                "link" => "https://www.facebook.com/WatamiPH",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
        );

        Partner::insert($partners);
    }
}
