<?php

use App\Team;
use Illuminate\Database\Seeder;

class TeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $teams = array(
            array(
                "id" => 1,
                "order" => 1,
                "name" => "Jovelyn Salcedo-Bandoquillo",
                "position" => "HR & Admin Manager",
                "image" => "6086767bc0abbjovelyn_bandoquillo.jpg",
                "status" => 1,
                "created_at" => NOW(),
                "updated_at" => NOW(),
            ),
            array(
                "id" => 2,
                "order" => 2,
                "name" => "Cristina Salgado",
                "position" => "HR & Admin Associate",
                "image" => "607698ff083fccristina_salgado.jpg",
                "status" => 1,
                "created_at" => "2021-01-19 15:19:52",
                "updated_at" => "2021-06-07 21:28:23",
            ),
            array(
                "id" => 4,
                "order" => 3,
                "name" => "Christopher Mariano",
                "position" => "Finance Manager",
                "image" => "60769907829dechristopher_mariano.jpg",
                "status" => 1,
                "created_at" => "2021-01-19 15:19:53",
                "updated_at" => "2021-06-07 21:28:23",
            ),
            array(
                "id" => 5,
                "order" => 4,
                "name" => "JC Sadongdong",
                "position" => "Inside Sales and Customer Relations Officer",
                "image" => "6076990e93793jc_sadongdong.jpg",
                "status" => 1,
                "created_at" => "2021-01-19 15:19:53",
                "updated_at" => "2021-04-14 20:26:06",
            ),
            array(
                "id" => 6,
                "order" => 5,
                "name" => "Reynaldo Tongco",
                "position" => "Office Helper",
                "image" => "6090aa6379d31reynaldo_tongco.jpg",
                "status" => 1,
                "created_at" => "2021-01-19 15:19:53",
                "updated_at" => "2021-05-04 14:58:59",
            ),
            array(
                "id" => 7,
                "order" => 6,
                "name" => "Robin Arias",
                "position" => "Mid-Sr. Web Developer (Team Lead)",
                "image" => "607fbcaeb52b8robin_arias.jpg",
                "status" => 1,
                "created_at" => NULL,
                "updated_at" => "2021-05-05 18:57:36",
            ),
            array(
                "id" => 8,
                "order" => 7,
                "name" => "Kaiser De Jesus",
                "position" => "Mid-Sr. Web Developer",
                "image" => "607699272a21bkaiser_de_jesus.jpg",
                "status" => 1,
                "created_at" => NULL,
                "updated_at" => "2021-04-15 16:12:57",
            ),
            array(
                "id" => 10,
                "order" => 9,
                "name" => "James Pinlac",
                "position" => "Jr. Web Developer",
                "image" => "6076992f096d5james_pinlac.jpg",
                "status" => 1,
                "created_at" => "2021-01-19 15:19:53",
                "updated_at" => "2021-04-14 20:26:39",
            ),
            array(
                "id" => 11,
                "order" => 8,
                "name" => "Lawrence Severino",
                "position" => "Jr. Web Developer",
                "image" => "6076993414dd4lawrence_severino.jpg",
                "status" => 1,
                "created_at" => NULL,
                "updated_at" => "2021-04-14 20:26:44",
            ),
            array(
                "id" => 12,
                "order" => 10,
                "name" => "Chinky Sarto",
                "position" => "Jr. Quality Assurance Specialist",
                "image" => "6076993806f74chinky_sarto.jpg",
                "status" => 1,
                "created_at" => NULL,
                "updated_at" => "2021-04-14 20:26:48",
            ),
            array(
                "id" => 13,
                "order" => 11,
                "name" => "Roland Pilar",
                "position" => "Mid-Sr. Mobile Game Developer",
                "image" => "6076993db4808roland_pilar.jpg",
                "status" => 1,
                "created_at" => NULL,
                "updated_at" => "2021-04-15 22:12:40",
            ),
            array(
                "id" => 15,
                "order" => 12,
                "name" => "Genesis Awa-ao",
                "position" => "Sr. Creatives Supervisor",
                "image" => "60769948ebac2genesis_awa_ao.jpg",
                "status" => 1,
                "created_at" => "2021-01-19 15:19:53",
                "updated_at" => "2021-04-14 20:27:05",
            ),
            array(
                "id" => 16,
                "order" => 13,
                "name" => "Linus Dalusag",
                "position" => "Sr. Graphic Artist",
                "image" => "6076994eb6292carl_linus_dalusag.jpg",
                "status" => 1,
                "created_at" => "2021-01-19 15:19:53",
                "updated_at" => "2021-04-15 22:13:15",
            ),
            array(
                "id" => 20,
                "order" => 14,
                "name" => "Maribeth Ogsila",
                "position" => "Jr. Sales Supervisor",
                "image" => "6080cd2193f7dmaribeth_ogsila.jpg",
                "status" => 1,
                "created_at" => "2021-01-19 15:19:53",
                "updated_at" => "2021-04-22 14:10:58",
            ),
            array(
                "id" => 21,
                "order" => 15,
                "name" => "John Reluya",
                "position" => "Jr. Account Manager",
                "image" => "6086766ae8866john_reluya.jpg",
                "status" => 1,
                "created_at" => "2021-01-19 15:19:53",
                "updated_at" => "2021-04-26 21:14:35",
            ),
            array(
                "id" => 22,
                "order" => 16,
                "name" => "Grace Parungao",
                "position" => "Sr. Account Manager",
                "image" => NULL,
                "status" => 1,
                "created_at" => NULL,
                "updated_at" => NULL,
            ),
            array(
                "id" => 31,
                "order" => 17,
                "name" => "Chesca Guevarra",
                "position" => "Digital Marketing Associate",
                "image" => "60769b4f3340dchesca_guevarra.jpg",
                "status" => 1,
                "created_at" => "2021-01-19 15:19:53",
                "updated_at" => "2021-04-14 20:35:43",
            ),
            array(
                "id" => 35,
                "order" => 18,
                "name" => "Rose Anne Manuel",
                "position" => "Jr. SEO Specialist",
                "image" => "6090aa71b7b2arose_anne_manuel.jpg",
                "status" => 1,
                "created_at" => "2021-01-19 15:19:54",
                "updated_at" => "2021-05-04 14:59:13",
            ),
            array(
                "id" => 36,
                "order" => 19,
                "name" => "Nina Bianca Nigos",
                "position" => "Jr. Brands Specialist",
                "image" => "60769b12f2741nina_bianca_nigos.jpg",
                "status" => 1,
                "created_at" => "2021-01-19 15:19:54",
                "updated_at" => "2021-04-14 20:34:43",
            ),
            array(
                "id" => 37,
                "order" => 20,
                "name" => "Cris Soriano",
                "position" => "Jr. Brands Specialist",
                "image" => "60769b0e2bdf0cris_soriano.jpg",
                "status" => 1,
                "created_at" => NULL,
                "updated_at" => "2021-04-14 20:34:38",
            ),
            array(
                "id" => 38,
                "order" => 21,
                "name" => "Jasmine Cargullo",
                "position" => "Jr. Brands Specialist",
                "image" => "60769b0938658jasmine_cargullo.jpg",
                "status" => 1,
                "created_at" => NULL,
                "updated_at" => "2021-04-14 20:34:33",
            ),
            array(
                "id" => 40,
                "order" => 22,
                "name" => "Joan Ubalde",
                "position" => "Jr. Data Analyst",
                "image" => "60769b211a62ajoan_ubalde.jpg",
                "status" => 1,
                "created_at" => NULL,
                "updated_at" => "2021-04-14 20:34:57",
            ),
        );

        Team::insert($teams);
    }
}
